apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddriver
  labels:
    app.kubernetes.io/name: clouddriver
    app.kubernetes.io/instance: clouddriver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clouddriver
      app.kubernetes.io/instance: clouddriver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clouddriver
        app.kubernetes.io/instance: clouddriver
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=50.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: gcr.io/spinnaker-marketplace/clouddriver:6.6.0-20200220090631
        name: clouddriver
        ports:
        - name: traffic-port
          containerPort: 7002
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 800m
            memory: 1200Mi
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: clouddriver-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
      terminationGracePeriodSeconds: 720
      volumes:
      - name: clouddriver-config-volume
        secret:
          defaultMode: 420
          secretName: clouddriver-config
      - name: spinnaker-secrets-volume
        secret:
          defaultMode: 420
          secretName: spinnaker-secrets

